spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mommyletter
    username: root
    password: ssafy
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: fAI8LZ3MWxC9aMFI12dY
            client-secret: 6K3J2eNh8I
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 300281625516-cg7s1da9ff78oa5rs08acf8e48q6p600.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

